config/routes.rb
Rails.application.routes.draw do

  get "/posts" => 'posts#index', :as => :posts
  post '/posts' => 'posts#create'
  get '/posts/new' => 'posts#new', :as => :new_post
  get '/posts/:id' => 'posts#show', :as => :post
  get '/posts/:id/edit' => 'posts#edit', :as => :edit_post

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :length => {:minimum => 5}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    # app/views/posts/index.html.erb
    # all of our blog posts

    # instance variables we define in our controller actions
    # get passed to the views
    @posts = Post.all

    render 'posts/index'
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save #=>

    if @post.save
      redirect_to post_path(@post) #/posts/1
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :author_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLv1Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<!-- How does form_for guess the correct URL?

1. Is the object persisted?
  Y -> Use the object's class to guess the post_path(@post) #=> posts#update
  N -> Use the object's class to guess the posts_path #=> posts#create -->


  <%= form_for(@post) do |form_builder| %>
    <p>
      <!-- errors and pre-filling the value for edit -->
      <%= form_builder.label :title %>
      <%= form_builder.text_field :title %>
    </p>

    <p>
      <%= form_builder.label :content %>
      <%= form_builder.text_area :content %>
    </p>

    <p>
      <%= form_builder.label :author_name %>
      <%= form_builder.text_field :author_name %>
    </p>


    <%= form_builder.submit %>
  <% end %>

app/views/posts/index.html.erb
<h1>My Blog Posts</h1>

<ol>
<% @posts.each do |post| %>
  <li>
    <!-- Using HTML to generate a link -->
    <!-- Least Abstract -->
    <!-- <a href="/posts/<%= post.id %>"><%= post.title %></a> -->
    <!-- Using Rails to generate a link -->
    <% # More abstract, using link_to but still hardcoding URL %>
    <%#= link_to(post.title, "/posts/#{post.id}") %>
    <% # More abstract, hard coding .id for post %>
    <%#= link_to(post.title, post_path(post.id)) %>
    <% # More abstract, not explicitly calling id on post %>
    <%= link_to(post.title, post_path(post)) %>
    <% # Most abstract, implicitly calling post_path based on object type of post %>
    <%#= link_to(post.title, post) %>
  </li>
<% end %>
</ol>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<style>
.field_with_errors {
  display: inline
}
.field_with_errors label{
  color: red
}
</style>

<!-- How does form_for guess the correct URL?

1. Is the object persisted?
  Y -> Use the object's class to guess the post_path(@post) #=> posts#update
  N -> Use the object's class to guess the posts_path #=> posts#create -->

<%= form_for(@post) do |form_builder| %>
  <p>
    <!-- errors and pre-filling the value for edit -->
    <%= form_builder.label :title %>
    <%= form_builder.text_field :title %>
  </p>

  <p>
    <%= form_builder.label :content %>
    <%= form_builder.text_area :content %>
  </p>

  <p>
    <%= form_builder.label :author_name %>
    <%= form_builder.text_field :author_name %>
  </p>

  <%= form_builder.submit %>
<% end %>

app/views/posts/non_abstract_new_forms.html.erb
<!--
1. form tag <form> - the lowest level of abstraction
2. form_tag - middle level of abtraction
3. form_for - highest of level of abstraction
-->

<!-- <form action="/posts" method="POST">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <p>
    <label for="post_title">
    <input type="text" name="title" id="post_title" value="<%= @post.title" %>/>
  </p>

  <p>
    <label for="post_content">
    <textarea name="content" id="post_content"></textarea>
  </p>

  <input type="submit" />
</form> -->

<!--
  <%#= form_tag(posts_path) do %>
  <p>
    <%# if @post.errors[:title].any? %>
      <span>You must include a title</span>
    <%# end %>

    <%#= label_tag 'title' %>
    <%#= text_field_tag 'post[title]', @post.title %>
  </p>

  <p>
    <%#= label_tag 'content' %>
    <%#= text_area_tag 'post[content]', @post.content %>
  </p>

  <p>
    <%#= label_tag 'author_name' %>
    <%#= text_field_tag 'post[author_name]', @post.author_name %>
  </p>

  <%#= submit_tag 'Submit' %>
<%# end %>
-->

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.content %></p>